import { defineConfig } from 'orval';

export default defineConfig({
  cartaisy: {
    input: {
      // Local snapshot of the backend OpenAPI spec (generated by `tsoa spec`
      // in the cartaisy-backend repo). Refresh it from the backend before
      // regenerating so the spec and generated client are committed together.
      target: './api-spec/swagger.json',
    },
    output: {
      mode: 'tags-split',
      target: './api/generated',
      client: 'react-query',
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: './api/apiClient.ts',
          name: 'customInstance',
        },
      },
    },
  },
});
